<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-D6LMSRTE" failures="1" tests="3" name="Personal Loan" time="0.046" errors="0" timestamp="2022-03-23T20:27:31 IST">
  <testcase classname="New.Demo" name="test1" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at New.Demo.test1(Demo.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="New.Lec134" name="sample1" time="0.002"/>
  <testcase classname="New.Lec134" name="sample2" time="0.001"/>
</testsuite> <!-- Personal Loan -->
